[env:m5stick-c-plus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

lib_deps =
    m5stack/M5Unified @ ^0.1.12
    m5stack/M5GFX @ ^0.1.12
    bblanchon/ArduinoJson @ ^6.21.3
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_M5STICKC_PLUS
